apiVersion: v1
kind: Service
metadata:
  labels:
    app: send
    component: send-dev
  name: send-dev
  namespace: online-send-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30860
  selector:
    app: send
    component: send-dev
    tier: backend
  sessionAffinity: None
  type: NodePort
