apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: send
    component: send-dev
    tier: backend
  name: send-dev
  namespace: online-send-dev 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: send
      component: send-dev
      tier: backend
  template:
    metadata:
      labels:
        app: send
        component: send-dev
        tier: backend
    spec:
      containers:
      - env:
        - name: CACHE_IGNORE
          value: js|html
        - name: CACHE_PUBLIC_EXPIRATION
          value: 3d
        image:  $PRIVATE_REPO/$PROJECT/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
        imagePullPolicy: Always
        name: ks-docs
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
